// Pixel character data and color palettes
// Extracted and adapted from pixel-character.html

export type ColorGrid = (string | null)[][];

// Color constants
export const COLORS: Record<string, string> = {
  B: '#1a1a1a',   // black/outline
  S: '#FFD5B8',   // skin
  K: '#F4C29A',   // skin shadow
  E: '#2c1810',   // eye dark
  W: '#ffffff',   // eye white
  M: '#e94560',   // mouth
  a: '#FF69B4',   // hair main (pink)
  b: '#E0559A',   // hair shadow (dark pink)
  c: '#FFB6D9',   // hair highlight (light pink)
  x: '#FFB5B5',   // blush
  r: '#e94560',   // red clothes
  d: '#b8364d',   // dark red
  w: '#f5f5f5',   // white clothes
  l: '#3b5998',   // blue clothes/hair
  n: '#8B4513',   // brown
  g: '#DAA520',   // gold
  p: '#9B59B6',   // purple
  G: '#2ECC71',   // green
};

// Parse a raw character map string into a ColorGrid
export function parseMap(raw: string): ColorGrid {
  return raw.trim().split('\n').map(row =>
    row.split('').map(c => {
      if (c === '.') return null;
      return COLORS[c] || null;
    })
  );
}

// ── 4 Character Maps (32×32) ──

const maidRaw = `
................................
................................
.............aaaaaaa.............
...........aaaaaaaaaaa...........
..........aaaaaaaaaaaaa..........
.........aaaaaaaaaaaaaaa.........
........aaaaaaSSSaaaaaa..........
.......aaaaaaSSSSSaaaaaa.........
......aaaaaaaSSSSSaaaaaaa........
......aaaaaaSESWSSaaaaaa.........
.....aaaaaSSEEWWSSSaaaaa.........
.....aaaaaSSEEWSSSSaaaaa.........
.....aaaaaSSSEEESSSaaaaa.........
.....aaaaaaSSSEESSSaaaaa.........
......aaaaaSSSSSSSaaaaaa.........
......aaaaaaSxxxSaaaaaa..........
.......aaaaaSxMxSaaaaaa..........
.......aaaawwwwwwwwwwaaa.........
........aawwwwwwwwwwwwaa.........
........wwwwwwwwwwwwwww..........
........wwwwwwwwwwwwwww..........
........wwwwwwwwwwwwwww..........
........wwwwddwwwwddwww..........
........wwwwddwwwwddwww..........
.........wwwwddddddwww...........
.........wwwwwwwwwwwww...........
..........wwwwwwwwwww............
...........ddddddddd.............
..........ddddddddddd............
.........ddddddddddddd...........
........ddddddddddddddd..........
................................`;

const swordRaw = `
................................
................................
............blllllllb............
...........blllllllllb...........
..........blllllllllllb..........
.........bllllllSSSllllb.........
........blllllSSSSSlllllb........
.......bllllllSSSSSlllllb........
......bllllllSESWSSllllb.........
......blllllSSEEWWSSllllb........
.....blllllSSEEWSSSllllb.........
.....blllllSSSEEESSllllb.........
.....bllllllSSSEESlllllb.........
......blllllSSSSSSlllllb.........
.......bllllSxxxSSllllb..........
........blllSxMxSllllb...........
.........blllGGGGlllb............
..........blGGGGGGGlb............
..........bGGGGGGGGGb............
..........bGnGnnGnGGb............
..........bGnGnnGnGGb............
..........bGGGGGGGGGb............
..........bGGGGGGGGGb............
..........bGGGggGGGGb............
...........bGGggGGGb.............
...........bGGGGGGGb.............
............bbrrrbb..............
............bbrrrbb..............
............bbrrrbb..............
............bbrrrbb..............
.............bbbbbb..............
................................`;

const mageRaw = `
................................
................................
.........pppppppppppp............
........pppppppppppppp...........
.......ppppppppppppppp...........
......pppppppSSSpppppp...........
......ppppppSSSSSpppppp..........
.....ppppppSSSSSppppppp..........
.....pppppSESWSSpppppp...........
....pppppSSEEWWSSppppp...........
....pppppSSEEWSSSppppp...........
....pppppSSSEEESpppppp...........
....ppppppSSSEESpppppp...........
.....pppppSSSSSSpppppp...........
.....ppppppSxxxSpppppp...........
......pppppSxMxSppppp............
.......pppprrrrrppp..............
.......ppprrrrrrrrppp............
.......pprrrrrrrrrrpp............
.......prpprrrrrrpprp............
.......prpprrrrrrpprp............
.......prppprrrrppprp............
.......prrpprrrrpprrp............
........rrrprrrrprrr.............
........rrrrrrrrrrrr.............
.........rrrrrrrrrr..............
.........dddddddddd..............
........dddddddddddd.............
........dddd..ddddd..............
........dd.....ddd...............
........dd....ddd................
................................`;

const catRaw = `
................................
................................
........a..aaaaaaaaaa..a........
.......aa.aaaaaaaaaaaa.aa.......
.......aaaaaaaaaaaaaaaaaa.......
.......aaaaaaaaaaaaaaaaaa.......
......aaaaaaSSSSSaaaaaaa........
......aaaaaaSSSSSaaaaaaa........
.....aaaaaaaSSSSSaaaaaaa........
.....aaaaaaSESWSSaaaaaaa........
....aaaaaaSSEEWWSSaaaaaa........
....aaaaaaSSEEWSSSaaaaaa........
....aaaaaaSSSEEESSaaaaaa........
....aaaaaaaSSSEESaaaaaaa........
.....aaaaaSSSSSSSaaaaaa.........
.....aaaaaaSxxxSaaaaaaa.........
......aaaaaSxMxSaaaaaa..........
.......aaaaarrrraaaaa...........
.......aaaarrrrrrraaaa..........
.......aaarrrrrrrrraaa..........
........arrrrrrrrrrra...........
........arrrrrrrrrrra...........
........arrBBrrBBrra............
........arrrrrrrrrra............
........arrrrrrrrrra............
.........arrrrrrrra.............
.........aarrrrrrraa............
.........ddddddddddd............
........ddddddddddddd...........
.......ddddddddddddddd..........
.......dddd...ddddd.............
................................`;

export interface CharacterDef {
  id: number;
  name: string;
  emoji: string;
  map?: ColorGrid;         // pixel chars only
  imagePath?: string;      // image chars: path relative to project root
  displayWidth?: number;   // image chars: target display width (default 200px)
}

export const CHARACTERS: CharacterDef[] = [
  { id: 0, name: '女仆', emoji: '🎀', map: parseMap(maidRaw) },
  { id: 1, name: '剑士', emoji: '⚔️', map: parseMap(swordRaw) },
  { id: 2, name: '魔法师', emoji: '🧙', map: parseMap(mageRaw) },
  { id: 3, name: '猫娘', emoji: '😺', map: parseMap(catRaw) },
  { id: 4, name: '椎名', emoji: '🌸', imagePath: 'assets/characters/shiiina.jpg', displayWidth: 300 },
];

// ── Animation variant maps ──
// Talk frames: different mouth shapes (only rows 16-18 change)
// Frame 0 = closed (base), Frame 1 = half-open, Frame 2 = open
// We generate these procedurally in animations.ts rather than storing full maps

// Walk frames: alternate legs (rows 25-31 differ)
// We generate these procedurally in animations.ts
